### ISSUE TITLE
Template cleanup job fails

### ISSUE THREAD

**Issue by tillahoffmann** [datatrail-jhu/python#14]
It looks like the template cleanup job no longer passes because permissions have changed. Specifically, the action doesn't have permission to open or approve pull requests (see [here](https://github.com/datatrail-jhu/python/actions/runs/8007270557/job/21870970974) for an example). The error message is:

```
Error: GitHub Actions is not permitted to create or approve pull requests.
```

Should we disable that job or try to fix it?

**Comment by cansavvy** [comment]
There's no need for that job long term. It's supposed to just run once when a repository is created to delete files that a repository doesn't need that's from the original template. So we can definitely just delete that gha.
