### ISSUE TITLE
R vs Python Chapter

### ISSUE THREAD

**Issue by cansavvy** [datatrail-jhu/python#2]
Candace will draft this chapter and then @tillahoffmann will help edit.

**Comment by cansavvy** [comment]
@howard you can request me to review first or send any questions my way. 

Make sure it is beginner friendly and jargon free

**Comment by howardbaek** [comment]
Do the students know object-oriented programming (OOP)? I'm borrowing material from https://rstudio.github.io/reticulate/articles/python_primer.html and debating whether to include OOP in the chapter.

**Comment by tillahoffmann** [comment]
Having an OOP discussion sounds great! Maybe the emphasis could be on "what is an object" and "how do I *use* them" (thinking of data frames here). And maybe less focus on class definition syntax, scoping, attributes vs properties, etc. What do you think?

**Comment by cansavvy** [comment]
👍 I generally am always in favor of application first and theory only if it helps understanding for the purposes of application.

**Comment by howardbaek** [comment]
Yes, I can go into the very basics of OOP ("what is an object", "what is a method", "what is an instance") as I find OOP to be very important to reading/writing Python, compared to R.
